### ISSUE TITLE
Theme Display Issues

### ISSUE THREAD

**Issue by spigglez** [duffey/spicetify-playlist-labels#14]
This is what it looks like with the Comfy theme. They stack on the right instead of extending side to side, even on full screen.

![image](https://github.com/duffey/spicetify-playlist-labels/assets/152670139/52b0cd02-1256-48d3-a4f3-cc574906324c)

_Originally posted by @spigglez in https://github.com/duffey/spicetify-playlist-labels/issues/8#issuecomment-1837634119_

**Comment by spigglez** [comment]
It does not show at all now.

**Comment by duffey** [comment]
Hm, it's working for me. I can try to reproduce if you post your About Spotify.

![image](https://github.com/duffey/spicetify-playlist-labels/assets/661081/dc352a88-870a-485c-b05b-3164ba870265)
![image](https://github.com/duffey/spicetify-playlist-labels/assets/661081/45143ecc-85df-47dc-815b-1e6b23c00940)
![image](https://github.com/duffey/spicetify-playlist-labels/assets/661081/738cfaf0-9551-45a6-b127-dface7c0dc9e)

**Comment by spigglez** [comment]
I am not sure what exactly happened but it works now.

**Comment by duffey** [comment]
Great! Thanks for the update

**Comment by spigglez** [comment]
Now it no longer has the x option to remove it from the playlists.

**Comment by spigglez** [comment]
Now it no longer has the x option to remove it from the playlists.

**Comment by duffey** [comment]
This is intentional. The X buttons have been removed in favor of shrinking the labels down and adding a context menu to remove tracks from playlists similar to the add context menu.
