### ISSUE TITLE
Star rating playlist covers (TODO: Add to repo and README)

### ISSUE THREAD

**Issue by WildGenius** [duffey/spicetify-playlist-labels#15]
Made these for myself to replicate the visible star ratings functionality, feel free to add them to the repo in any way you see fit. Thanks to everyone involved in both old and new star ratings extensions, as well as this one!
<details> <summary>All are .png 640x640, per Spotify guidelines</summary>

![1](https://github.com/duffey/spicetify-playlist-labels/assets/8071762/4ad1b335-8c79-4686-8481-62ad85d02fce)
![2](https://github.com/duffey/spicetify-playlist-labels/assets/8071762/5e74b253-80b3-430a-bb0e-870367922a60)
![3](https://github.com/duffey/spicetify-playlist-labels/assets/8071762/107ff699-7166-4c86-9f27-64bb02f311dd)
![4](https://github.com/duffey/spicetify-playlist-labels/assets/8071762/16b1bc6a-8686-4b72-a0b8-63fe61dc2ad0)
![5](https://github.com/duffey/spicetify-playlist-labels/assets/8071762/4b9a61e3-31b6-42d7-800f-4369b258f054)
![banned](https://github.com/duffey/spicetify-playlist-labels/assets/8071762/cd9793e1-7d95-4efa-a8e6-a6db6e1b0419)

</details>

**Comment by duffey** [comment]
Wow, excellent!

**Comment by duffey** [comment]
Perhaps adding them to the repo and README of both extensions would be good.

**Comment by duffey** [comment]
Also, I realize rating tracks this way is a little slower as it takes two clicks and scrolling through a context menu. It's half an idea, but perhaps a special label for ratings could be done somehow.

**Comment by duffey** [comment]
Added to the README. Thanks so much! :)
