### ISSUE TITLE
View on playlists

### ISSUE THREAD

**Issue by aman0224** [duffey/spicetify-playlist-labels#17]
it covers the like button in playlist view
![s1](https://github.com/duffey/spicetify-playlist-labels/assets/123305514/dfb5d668-f56a-4980-8bdd-e7baf6576a6e)
![s2](https://github.com/duffey/spicetify-playlist-labels/assets/123305514/86db2638-e67f-4c58-8e0c-1ccde3c90a81)

**Comment by duffey** [comment]
Sorry, these extensions weren't designed to work together. I suggest using just this one.
