### ISSUE TITLE
Cant see other saved playlist that were not created by me anymore

### ISSUE THREAD

**Issue by Drewjrr** [duffey/spicetify-playlist-labels#18]
I was able to see my friends playlist which was really nice bc I can see what songs they added from an album but now i cant 
Was this one of the things u removed with the new update? and if so is it coming back?

**Comment by duffey** [comment]
Yeah, I removed it. I tried to make the labels shown consist with the new "Add to playlist" menu. I think I will add it back with the toggle again.

![image](https://github.com/duffey/spicetify-playlist-labels/assets/661081/2eaf32f9-99f0-4869-a766-154b139550c9)

**Comment by duffey** [comment]
I will leave this issue open as a reminder to add it back.

**Comment by Drewjrr** [comment]
oh ok..my bad

**Comment by duffey** [comment]
Done! :)
