### ISSUE TITLE
change it so that it doesn't show the playlist if it is a ranking e.g. if the playlist is called "0.5", "1.0", "1.5" etc

### ISSUE THREAD

**Issue by brimell** [duffey/spicetify-playlist-labels#20]
I am using both your star rating system and your playlist labels extension but there is a clash as it will show both the rating with stars and the icon of the playlist inside the "Rated" folder

**Comment by duffey** [comment]
Not sure if you mean modify this extension or the other one. Many people reported problems using both. I suggest using just this one. Also, the new "Add to playlist" menu makes it easy to update the rating.

**Comment by duffey** [comment]
Sorry, but I've archived the other repo because I don't want to support any interaction between the two.
