### ISSUE TITLE
albums rating not working and giving errors

### ISSUE THREAD

**Issue by brimell** [duffey/spicetify-playlist-labels#21]
star-ratings.js?time=1706045411034:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'albumUnion')
    at star-ratings.js?time=1706045411034:1:10945
    at tt (star-ratings.js?time=1706045411034:1:11079)
    at st (star-ratings.js?time=1706045411034:1:17070)
    at async star-ratings.js?time=1706045411034:1:1980

**Comment by duffey** [comment]
Sorry, I'm no longer working on the star ratings extension. Maybe an update broke it. If someone fixes it I will merge it.
