### ISSUE TITLE
Debilitated responsiveness on startup.

### ISSUE THREAD

**Issue by N72826** [duffey/spicetify-playlist-labels#23]
Absolutely love this extension, so I really appreciate you for creating it. Sadly, the extension seems to be responsible for crippling responsiveness when booting up Spotify (requires me to wait a frustrating amount of time until it's not bricked anymore in order to play/pause or navigate playlists menus). 

I didn't know what was causing it at first. I suspected it was going to be a presumably heavier thing such as the fullscreen player or the theme I'm using. After uninstalling each extension one by one, I immediately noticed the difference after reloading with this extension uninstalled. I would really like to continue using it, but I'm extremely impatient so I have to let go of it/only install it when trying to clean out my spotify duplicates.

**Comment by duffey** [comment]
It downloads your entire playlist library and liked songs on startup in order to figure out what tracks are in what playlist. I'm not sure of a way around this at the moment.

**Comment by duffey** [comment]
I discovered the official APIs have a "snapshot_id" for playlists which may indicate whether it was updated or not. Maybe I can cache the playlist data and then only get new data if this has changed. I will comment updates here.

**Comment by duffey** [comment]
@N72826 
Hey, I just added a bunch of caching which should solve the issue. Hopefully it doesn't break anything, included actually updating when necessary. Can you check as soon as you get the update and let me know if it's faster? (It will still be slow the first time you start because it needs to build the cache.)

**Comment by N72826** [comment]
@duffey now they aren't appearing and I can't even see an error in the developer console.

**Comment by duffey** [comment]
OK, I took another crack at caching with IndexedDB this time. Please let me know if it works!

**Comment by duffey** [comment]
OK, this should be solved since I caching data. Responsiveness to changes in playlists can be optimized a bit further.
