### ISSUE TITLE
Obscured track names on artist page

### ISSUE THREAD

**Issue by Satanarious** [duffey/spicetify-playlist-labels#26]
The track names on the artist page are almost entirely obscured. Even though there's only 4 playlist displayed at most in the image below, but it still takes so much space.

![image](https://github.com/duffey/spicetify-playlist-labels/assets/42642682/cdad999e-52c1-476f-bcc9-1bd56fa781fa)

**Comment by duffey** [comment]
Yeah, I fixed the extension so it only takes up the minimum space necessary.
