### ISSUE TITLE
Consider using an overflow menu when there is not enough horizontal space

### ISSUE THREAD

**Issue by D3SOX** [duffey/spicetify-playlist-labels#27]
When a song is in many playlist it get's sometimes so cluttered that the names get abbreviated which is kinda bad in my opinion

![image](https://github.com/duffey/spicetify-playlist-labels/assets/24937357/5b684ea5-d890-46eb-a885-d1832ad8e374)

<details><summary>When I make the window more narrow it gets even worse</summary>
<p>

![image](https://github.com/duffey/spicetify-playlist-labels/assets/24937357/aa3f6d9f-d89f-4df9-b172-951dab43d6d9)

</p>
</details> 

I would suggest (maybe using media queries) make it that the last is like a (+2 more) and when you hover you see the ones in a tooltip or on click in a modal

Concept UI design from Discord
![image](https://github.com/duffey/spicetify-playlist-labels/assets/24937357/d57477c3-4845-43c1-ab81-5a5e3b1b431a)

**Comment by duffey** [comment]
Yeah, I completely agree. I thought about this before and I have just been reluctant to add it yet because I don't have as many playlists and I wasn't sure what design to go with. Now that I know somebody needs it I might make it soon.

**Comment by D3SOX** [comment]
Couldn't really tell until now because it's a bit finicky to get them even working in Spotify version with the old library. It feels a bit random when they work and when they don't.

**Comment by duffey** [comment]
The new Spotify has a plus icon instead of a heart. You might need to reset your features by clicking the button at the bottom here:

![image](https://github.com/duffey/spicetify-playlist-labels/assets/661081/43423b56-7c17-4d31-aee0-076bbeb19882)

**Comment by D3SOX** [comment]
I'm using an old version because I want the old library maybe there are some incompatibilities

**Comment by D3SOX** [comment]
That must be the case because currently they don't work at all.

Btw, the Spicetify version I'm using is `2.34.1` because I've had some issues with later versions.

I don't know a way on Windows/Mac but [I made this](https://github.com/D3SOX/spotify-old-library-linux) to get the old library on Linux

The thing is I'm not sure how much effort it would be to make it consistently work on that version and I don't think it's of your interest to support it. The only thing I can offer is to pledge something for it
