### ISSUE TITLE
Column not being shown

### ISSUE THREAD

**Issue by jeroentvb** [duffey/spicetify-playlist-labels#7]
The labels column doesn't show up for me.
Using the latest spotify and spicetify on windows 10.
Installed via the marketplace.

**Comment by duffey** [comment]
What's your Spotify version and Spicetify version? Mine is working below

![image](https://github.com/duffey/spicetify-playlist-labels/assets/661081/ce68f045-adcc-40fb-891f-3f5a5fb0164f)

**Comment by jeroentvb** [comment]
Spotify voor Windows (64-bits)
1.2.24.756.g7a7fc7f0
Spicetify v2.27.1

**Comment by jeroentvb** [comment]
I do seem to be getting these kinds of errors from the extension in the console, not sure if that's what's causing the issue?
![image](https://github.com/duffey/spicetify-playlist-labels/assets/36192730/9a4e4ad9-0b6c-4c0a-88a2-7e5f72e66f4f)

**Comment by duffey** [comment]
Oh, I recognize that error from an issue I fixed before. Whenever trying to get a playlist color that has already been requested that happens. I cache the requests but in this case it's not working. Not sure why yet. Will investigate.

**Comment by duffey** [comment]
Well, I'm now displaying playlist images instead of colored labels, so this should no longer be an issue. Please reopen if you have problems!
