### ISSUE TITLE
Label may not show on certain theme, and some bugs.

### ISSUE THREAD

**Issue by Cookie755233** [duffey/spicetify-playlist-labels#8]
I'm using **Sleek** theme, and found the labels will not show properly as the following picture shows
<img width="1523" alt="image" src="https://github.com/duffey/spicetify-playlist-labels/assets/85786140/b99b10b5-458b-419e-b5ef-3f78eedbf8fa">

Also, might be theme-related bug I'm not so sure, when scrolling down playlist, the label will not follow. I will have to turn off and on after scrolling a bit.

**Comment by rharley99** [comment]
I'm having the same issue with the default dynamic theme!

**Comment by rharley99** [comment]
I'm having the same issue with the default dynamic theme!!
<img width="1052" alt="spicetify" src="https://github.com/duffey/spicetify-playlist-labels/assets/110076974/52b87080-5925-4137-940a-5adea90837ab">

**Comment by duffey** [comment]
Thanks for reporting! Should be fixed now.

**Comment by rharley99** [comment]
> Thanks for reporting! Should be fixed now. Please reopen if not.

It's working, thanks so much!

**Comment by spigglez** [comment]
This is what it looks like with the Comfy theme. They stack on the right instead of extending side to side, even on full screen.


![image](https://github.com/duffey/spicetify-playlist-labels/assets/152670139/52b0cd02-1256-48d3-a4f3-cc574906324c)
