### ISSUE TITLE
Will not show up

### ISSUE THREAD

**Issue by spigglez** [duffey/spicetify-playlist-labels#9]
I turned off my theme, I deleted all of my extensions. There is still no evidence that the extension even downloaded no matter what I remove this feature will not show.
![image](https://github.com/duffey/spicetify-playlist-labels/assets/152670139/84101f4c-86de-46e6-9b0a-e8c8c7cf2693)
![image](https://github.com/duffey/spicetify-playlist-labels/assets/152670139/ede9a056-4e5e-4c68-a4da-914d966065f6)

**Comment by duffey** [comment]
Hm, I think it is running fine for me with the latest Spotify and Spicetify. Can you post your info under "Help -> About Spotify"?

![image](https://github.com/duffey/spicetify-playlist-labels/assets/661081/0841c1e7-b901-4316-8d2d-03afc3eaccad)

**Comment by duffey** [comment]
What OS are you on? I can try to reproduce it.

**Comment by spigglez** [comment]
I got it working. I just completely redownloaded spotify and spicetify. Thanks for your willingness to assist. It was on Windows 11.

**Comment by duffey** [comment]
Those errors are unrelated to the extension. I'm confident the extension is working on Windows, so I suggest asking for help in the Discord as it's a Spicetify issue.
